-- Insert seed resources
INSERT INTO "Resource" (name, url, description, category, price, is_open_source, source, status, published_at) VALUES
-- Foundation Models
('ChatGPT', 'https://chat.openai.com', 'OpenAI开发的对话式AI助手，支持文本生成、代码编写、问答等多种任务', 'foundation-models', 'Freemium', false, 'seed', 'published', NOW()),
('Claude', 'https://claude.ai', 'Anthropic开发的AI助手，以安全性和长文本处理能力著称', 'foundation-models', 'Freemium', false, 'seed', 'published', NOW()),
('Gemini', 'https://gemini.google.com', 'Google开发的多模态AI模型，支持文本、图像、代码理解', 'foundation-models', 'Freemium', false, 'seed', 'published', NOW()),
('文心一言', 'https://yiyan.baidu.com', '百度开发的AI大语言模型，针对中文优化', 'foundation-models', 'Freemium', false, 'seed', 'published', NOW()),
('通义千问', 'https://tongyi.aliyun.com', '阿里云开发的大语言模型，支持多轮对话和复杂推理', 'foundation-models', 'Freemium', false, 'seed', 'published', NOW()),
('Kimi', 'https://kimi.moonshot.cn', '月之暗面开发的长文本AI助手，支持超长上下文', 'foundation-models', 'Freemium', false, 'seed', 'published', NOW()),
('Llama', 'https://llama.meta.com', 'Meta开源的大语言模型系列，可本地部署', 'foundation-models', 'Free', true, 'seed', 'published', NOW()),
('Mistral', 'https://mistral.ai', '法国Mistral AI开发的高性能开源大模型', 'foundation-models', 'Freemium', true, 'seed', 'published', NOW()),
('DeepSeek', 'https://chat.deepseek.com', '深度求索开发的AI助手，在代码和数学方面表现优异', 'foundation-models', 'Freemium', false, 'seed', 'published', NOW()),
('智谱清言', 'https://chatglm.cn', '智谱AI开发的ChatGLM系列模型对话平台', 'foundation-models', 'Freemium', false, 'seed', 'published', NOW()),
('Perplexity', 'https://www.perplexity.ai', 'AI搜索引擎，提供带引用来源的智能问答', 'foundation-models', 'Freemium', false, 'seed', 'published', NOW()),
('Poe', 'https://poe.com', 'Quora推出的AI聊天平台，聚合多个大模型', 'foundation-models', 'Freemium', false, 'seed', 'published', NOW()),
('HuggingChat', 'https://huggingface.co/chat', 'Hugging Face提供的开源模型聊天界面', 'foundation-models', 'Free', true, 'seed', 'published', NOW()),
('Grok', 'https://grok.x.ai', 'xAI开发的AI助手，集成X平台实时信息', 'foundation-models', 'Paid', false, 'seed', 'published', NOW()),
('Cohere', 'https://cohere.com', '企业级大语言模型API平台，专注文本生成和嵌入', 'foundation-models', 'Freemium', false, 'seed', 'published', NOW()),

-- Coding
('GitHub Copilot', 'https://github.com/features/copilot', 'GitHub与OpenAI合作的AI编程助手，提供代码补全和建议', 'coding', 'Paid', false, 'seed', 'published', NOW()),
('Cursor', 'https://cursor.sh', '基于VS Code的AI代码编辑器，支持代码生成和重构', 'coding', 'Freemium', false, 'seed', 'published', NOW()),
('Codeium', 'https://codeium.com', '免费的AI代码补全工具，支持70+编程语言', 'coding', 'Free', false, 'seed', 'published', NOW()),
('Tabnine', 'https://www.tabnine.com', 'AI代码补全工具，支持本地和云端部署', 'coding', 'Freemium', false, 'seed', 'published', NOW()),
('Amazon CodeWhisperer', 'https://aws.amazon.com/codewhisperer', 'AWS提供的AI代码生成服务，对个人开发者免费', 'coding', 'Freemium', false, 'seed', 'published', NOW()),
('Replit Ghostwriter', 'https://replit.com/site/ghostwriter', 'Replit集成的AI编程助手，支持代码生成和解释', 'coding', 'Paid', false, 'seed', 'published', NOW()),
('JetBrains AI', 'https://www.jetbrains.com/ai', 'JetBrains IDE集成的AI助手，支持代码生成和重构', 'coding', 'Paid', false, 'seed', 'published', NOW()),
('Sourcegraph Cody', 'https://sourcegraph.com/cody', '基于代码库的AI编程助手，支持代码搜索和生成', 'coding', 'Freemium', false, 'seed', 'published', NOW()),
('Continue', 'https://continue.dev', '开源的AI代码助手VS Code插件，支持多种模型', 'coding', 'Free', true, 'seed', 'published', NOW()),
('Aider', 'https://aider.chat', '命令行AI编程助手，支持多文件编辑和Git集成', 'coding', 'Free', true, 'seed', 'published', NOW()),
('Supermaven', 'https://supermaven.com', '高速AI代码补全工具，响应速度快', 'coding', 'Freemium', false, 'seed', 'published', NOW()),
('CodeGeeX', 'https://codegeex.cn', '智谱AI开发的代码生成模型，支持多种编程语言', 'coding', 'Free', true, 'seed', 'published', NOW()),
('通义灵码', 'https://tongyi.aliyun.com/lingma', '阿里云推出的AI编程助手，针对中文开发者优化', 'coding', 'Free', false, 'seed', 'published', NOW()),
('iFlyCode', 'https://iflycode.xfyun.cn', '科大讯飞开发的智能编程助手', 'coding', 'Freemium', false, 'seed', 'published', NOW()),
('CodeRabbit', 'https://coderabbit.ai', 'AI代码审查工具，自动分析Pull Request', 'coding', 'Freemium', false, 'seed', 'published', NOW()),

-- Image
('Midjourney', 'https://www.midjourney.com', '高质量的AI图像生成工具，通过Discord使用', 'image', 'Paid', false, 'seed', 'published', NOW()),
('DALL-E 3', 'https://openai.com/dall-e-3', 'OpenAI的AI图像生成模型，集成在ChatGPT中', 'image', 'Freemium', false, 'seed', 'published', NOW()),
('Stable Diffusion', 'https://stability.ai', '开源的AI图像生成模型，可本地部署', 'image', 'Free', true, 'seed', 'published', NOW()),
('Adobe Firefly', 'https://www.adobe.com/products/firefly.html', 'Adobe的AI创意工具，支持图像生成和编辑', 'image', 'Freemium', false, 'seed', 'published', NOW()),
('Leonardo.ai', 'https://leonardo.ai', '游戏资产和创意图像生成平台', 'image', 'Freemium', false, 'seed', 'published', NOW()),
('Canva AI', 'https://www.canva.com/ai-image-generator', 'Canva集成的AI图像生成工具', 'image', 'Freemium', false, 'seed', 'published', NOW()),
('Remove.bg', 'https://www.remove.bg', '自动去除图片背景的AI工具', 'image', 'Freemium', false, 'seed', 'published', NOW()),
('Upscayl', 'https://upscayl.org', '开源的AI图像放大工具', 'image', 'Free', true, 'seed', 'published', NOW()),
('Clipdrop', 'https://clipdrop.co', 'Stability AI的图像编辑工具套件', 'image', 'Freemium', false, 'seed', 'published', NOW()),
('Playground AI', 'https://playgroundai.com', '免费的AI图像生成和编辑平台', 'image', 'Freemium', false, 'seed', 'published', NOW()),
('Ideogram', 'https://ideogram.ai', '擅长生成带文字的AI图像工具', 'image', 'Freemium', false, 'seed', 'published', NOW()),
('FLUX', 'https://blackforestlabs.ai', 'Black Forest Labs开发的高质量图像生成模型', 'image', 'Freemium', true, 'seed', 'published', NOW()),
('Krea', 'https://www.krea.ai', '实时AI图像生成和编辑平台', 'image', 'Freemium', false, 'seed', 'published', NOW()),
('Recraft', 'https://www.recraft.ai', '专业矢量图形和插画AI生成工具', 'image', 'Freemium', false, 'seed', 'published', NOW()),
('文心一格', 'https://yige.baidu.com', '百度的AI艺术和创意辅助平台', 'image', 'Freemium', false, 'seed', 'published', NOW()),

-- Writing
('Notion AI', 'https://www.notion.so/product/ai', 'Notion集成的AI写作助手，支持内容生成和编辑', 'writing', 'Paid', false, 'seed', 'published', NOW()),
('Grammarly', 'https://www.grammarly.com', 'AI驱动的写作辅助工具，检查语法和风格', 'writing', 'Freemium', false, 'seed', 'published', NOW()),
('Jasper', 'https://www.jasper.ai', '企业级AI写作平台，支持营销内容创作', 'writing', 'Paid', false, 'seed', 'published', NOW()),
('Copy.ai', 'https://www.copy.ai', 'AI营销文案生成工具', 'writing', 'Freemium', false, 'seed', 'published', NOW()),
('Writesonic', 'https://writesonic.com', 'AI内容创作平台，支持博客、广告等多种格式', 'writing', 'Freemium', false, 'seed', 'published', NOW()),
('Rytr', 'https://rytr.me', '经济实惠的AI写作助手', 'writing', 'Freemium', false, 'seed', 'published', NOW()),
('QuillBot', 'https://quillbot.com', 'AI改写和润色工具', 'writing', 'Freemium', false, 'seed', 'published', NOW()),
('Wordtune', 'https://www.wordtune.com', 'AI写作和改写助手', 'writing', 'Freemium', false, 'seed', 'published', NOW()),
('Hemingway Editor', 'https://hemingwayapp.com', '写作可读性分析和改进工具', 'writing', 'Freemium', false, 'seed', 'published', NOW()),
('Sudowrite', 'https://www.sudowrite.com', '专为小说创作设计的AI写作工具', 'writing', 'Paid', false, 'seed', 'published', NOW()),
('NovelAI', 'https://novelai.net', 'AI故事创作和图像生成平台', 'writing', 'Paid', false, 'seed', 'published', NOW()),
('Jenni AI', 'https://jenni.ai', 'AI学术写作助手', 'writing', 'Freemium', false, 'seed', 'published', NOW()),
('Moonbeam', 'https://www.gomoonbeam.com', 'AI长文写作工具，专注博客和文章', 'writing', 'Freemium', false, 'seed', 'published', NOW()),
('HyperWrite', 'https://www.hyperwriteai.com', '个人AI写作助手，提供实时建议', 'writing', 'Freemium', false, 'seed', 'published', NOW()),
('秘塔写作猫', 'https://xiezuocat.com', '中文AI写作辅助工具，支持改写和校对', 'writing', 'Freemium', false, 'seed', 'published', NOW()),

-- Office
('Gamma', 'https://gamma.app', 'AI驱动的演示文稿生成工具', 'office', 'Freemium', false, 'seed', 'published', NOW()),
('Beautiful.ai', 'https://www.beautiful.ai', '智能演示文稿设计工具', 'office', 'Paid', false, 'seed', 'published', NOW()),
('Tome', 'https://tome.app', 'AI叙事和演示平台', 'office', 'Freemium', false, 'seed', 'published', NOW()),
('Microsoft Copilot', 'https://copilot.microsoft.com', '微软Office套件集成的AI助手', 'office', 'Paid', false, 'seed', 'published', NOW()),
('Google Workspace AI', 'https://workspace.google.com', 'Google文档、表格、幻灯片的AI功能', 'office', 'Paid', false, 'seed', 'published', NOW()),
('Otter.ai', 'https://otter.ai', 'AI会议记录和转录工具', 'office', 'Freemium', false, 'seed', 'published', NOW()),
('Fireflies.ai', 'https://fireflies.ai', 'AI会议助手，自动记录和分析会议', 'office', 'Freemium', false, 'seed', 'published', NOW()),
('Fathom', 'https://fathom.video', '免费的AI会议记录工具', 'office', 'Free', false, 'seed', 'published', NOW()),
('Mem.ai', 'https://mem.ai', 'AI驱动的笔记和知识管理工具', 'office', 'Freemium', false, 'seed', 'published', NOW()),
('Taskade', 'https://www.taskade.com', 'AI项目管理和协作平台', 'office', 'Freemium', false, 'seed', 'published', NOW()),
('Motion', 'https://www.usemotion.com', 'AI日程规划和任务管理工具', 'office', 'Paid', false, 'seed', 'published', NOW()),
('Reclaim.ai', 'https://reclaim.ai', '智能日程安排助手', 'office', 'Freemium', false, 'seed', 'published', NOW()),
('Clockwise', 'https://www.getclockwise.com', '团队日程优化工具', 'office', 'Freemium', false, 'seed', 'published', NOW()),
('SlidesAI', 'https://www.slidesai.io', 'Google幻灯片AI生成插件', 'office', 'Freemium', false, 'seed', 'published', NOW()),
('Plus AI', 'https://www.plusdocs.com', 'Google幻灯片AI生成工具', 'office', 'Paid', false, 'seed', 'published', NOW()),

-- Knowledge
('Obsidian', 'https://obsidian.md', '强大的本地知识库工具，支持丰富的插件生态', 'knowledge', 'Freemium', false, 'seed', 'published', NOW()),
('Notion', 'https://www.notion.so', '全能型工作空间和知识管理工具', 'knowledge', 'Freemium', false, 'seed', 'published', NOW()),
('Logseq', 'https://logseq.com', '开源的隐私优先知识管理工具', 'knowledge', 'Free', true, 'seed', 'published', NOW()),
('Roam Research', 'https://roamresearch.com', '双向链接笔记工具，支持网络式思维', 'knowledge', 'Paid', false, 'seed', 'published', NOW()),
('Reflect', 'https://reflect.app', 'AI增强的笔记工具，自动整理和关联笔记', 'knowledge', 'Paid', false, 'seed', 'published', NOW()),
('Capacities', 'https://capacities.io', '对象导向的笔记和知识管理工具', 'knowledge', 'Freemium', false, 'seed', 'published', NOW()),
('Anytype', 'https://anytype.io', '本地优先的P2P知识管理工具', 'knowledge', 'Free', true, 'seed', 'published', NOW()),
('AFFiNE', 'https://affine.pro', '开源的Notion和Miro替代品', 'knowledge', 'Free', true, 'seed', 'published', NOW()),
('AppFlowy', 'https://www.appflowy.io', '开源的Notion替代品', 'knowledge', 'Free', true, 'seed', 'published', NOW()),
('SiYuan', 'https://b3log.org/siyuan', '本地优先的个人知识管理系统', 'knowledge', 'Freemium', true, 'seed', 'published', NOW()),
('Heptabase', 'https://heptabase.com', '视觉化知识管理工具，支持白板', 'knowledge', 'Paid', false, 'seed', 'published', NOW()),
('Scrintal', 'https://scrintal.com', '视觉化思考和知识管理工具', 'knowledge', 'Paid', false, 'seed', 'published', NOW()),
('Tana', 'https://tana.inc', 'AI原生知识管理工具', 'knowledge', 'Paid', false, 'seed', 'published', NOW()),
('Amie', 'https://amie.so', 'AI驱动的日历和任务管理工具', 'knowledge', 'Freemium', false, 'seed', 'published', NOW()),
('Twine', 'https://twine.notion.site', 'AI驱动的知识整理工具', 'knowledge', 'Paid', false, 'seed', 'published', NOW()),

-- Research
('Consensus', 'https://consensus.app', 'AI驱动的科学研究搜索引擎', 'research', 'Freemium', false, 'seed', 'published', NOW()),
('Elicit', 'https://elicit.org', 'AI研究助手，自动化文献综述', 'research', 'Freemium', false, 'seed', 'published', NOW()),
('SciSpace', 'https://typeset.io', 'AI学术阅读和写作平台', 'research', 'Freemium', false, 'seed', 'published', NOW()),
('Semantic Scholar', 'https://www.semanticscholar.org', 'AI驱动的学术搜索引擎', 'research', 'Free', false, 'seed', 'published', NOW()),
('Connected Papers', 'https://www.connectedpapers.com', '可视化论文关联图谱工具', 'research', 'Freemium', false, 'seed', 'published', NOW()),
('ResearchRabbit', 'https://www.researchrabbit.ai', 'AI文献发现和可视化工具', 'research', 'Free', false, 'seed', 'published', NOW()),
('Litmaps', 'https://www.litmaps.com', '文献管理和发现工具', 'research', 'Freemium', false, 'seed', 'published', NOW()),
('Inciteful', 'https://inciteful.xyz', '免费的研究发现和可视化工具', 'research', 'Free', false, 'seed', 'published', NOW()),
('Paperpile', 'https://paperpile.com', 'AI驱动的文献管理工具', 'research', 'Paid', false, 'seed', 'published', NOW()),
('Zotero', 'https://www.zotero.org', '开源的文献管理工具', 'research', 'Free', true, 'seed', 'published', NOW()),
('Mendeley', 'https://www.mendeley.com', 'Elsevier的文献管理和学术社交平台', 'research', 'Free', false, 'seed', 'published', NOW()),
('Trinka', 'https://www.trinka.ai', 'AI学术写作和语法检查工具', 'research', 'Freemium', false, 'seed', 'published', NOW()),
('Paperpal', 'https://paperpal.com', 'AI学术写作助手', 'research', 'Freemium', false, 'seed', 'published', NOW()),
('Writefull', 'https://writefull.com', 'AI学术语言检查工具', 'research', 'Freemium', false, 'seed', 'published', NOW()),
('Scholarcy', 'https://www.scholarcy.com', 'AI文献摘要和知识提取工具', 'research', 'Freemium', false, 'seed', 'published', NOW()),

-- Robotics
('Figure AI', 'https://www.figure.ai', '开发通用人形机器人的AI公司', 'robotics', 'Paid', false, 'seed', 'published', NOW()),
('Tesla Optimus', 'https://www.tesla.com/optimus', '特斯拉人形机器人项目', 'robotics', 'Paid', false, 'seed', 'published', NOW()),
('Boston Dynamics', 'https://www.bostondynamics.com', '领先的动力学机器人公司，Spot和Atlas', 'robotics', 'Paid', false, 'seed', 'published', NOW()),
('Unitree Robotics', 'https://www.unitree.com', '宇树科技，四足机器人和人形机器人', 'robotics', 'Paid', false, 'seed', 'published', NOW()),
('Agility Robotics', 'https://www.agilityrobotics.com', 'Digit人形机器人开发公司', 'robotics', 'Paid', false, 'seed', 'published', NOW()),
('1X Technologies', 'https://www.1x.tech', '开发家用机器人的AI公司', 'robotics', 'Paid', false, 'seed', 'published', NOW()),
('Apptronik', 'https://www.apptronik.com', 'Apollo人形机器人开发公司', 'robotics', 'Paid', false, 'seed', 'published', NOW()),
('Fourier Intelligence', 'https://www.fourierintelligence.com', '傅利叶智能，康复机器人和人形机器人', 'robotics', 'Paid', false, 'seed', 'published', NOW()),
('Covariant', 'https://covariant.ai', 'AI机器人大脑，工业自动化', 'robotics', 'Paid', false, 'seed', 'published', NOW()),
('Robotic Research', 'https://www.roboticresearch.com', '自动驾驶和机器人技术公司', 'robotics', 'Paid', false, 'seed', 'published', NOW()),
('NVIDIA Isaac', 'https://developer.nvidia.com/isaac', 'NVIDIA机器人开发平台', 'robotics', 'Free', false, 'seed', 'published', NOW()),
('ROS', 'https://www.ros.org', '机器人操作系统，开源机器人软件框架', 'robotics', 'Free', true, 'seed', 'published', NOW()),
('Gazebo', 'https://gazebosim.org', '开源机器人仿真平台', 'robotics', 'Free', true, 'seed', 'published', NOW()),
('MoveIt', 'https://moveit.ros.org', '开源机器人运动规划框架', 'robotics', 'Free', true, 'seed', 'published', NOW()),
('OpenAI Robot', 'https://openai.com/research/robotics', 'OpenAI机器人研究成果', 'robotics', 'Free', false, 'seed', 'published', NOW()),

-- Entertainment
('Character.AI', 'https://character.ai', '创建和与AI角色对话的平台', 'entertainment', 'Freemium', false, 'seed', 'published', NOW()),
('Replika', 'https://replika.ai', 'AI伴侣应用，提供情感支持', 'entertainment', 'Freemium', false, 'seed', 'published', NOW()),
('Anima', 'https://myanima.ai', 'AI虚拟朋友和伴侣', 'entertainment', 'Freemium', false, 'seed', 'published', NOW()),
('Chai', 'https://chai.ml', '与AI聊天机器人对话的平台', 'entertainment', 'Freemium', false, 'seed', 'published', NOW()),
('Janitor AI', 'https://janitorai.com', '角色扮演AI聊天平台', 'entertainment', 'Freemium', false, 'seed', 'published', NOW()),
('Silly Tavern', 'https://sillytavern.app', '开源的AI角色扮演界面', 'entertainment', 'Free', true, 'seed', 'published', NOW()),
('Agnaistic', 'https://agnai.chat', '开源的AI角色扮演平台', 'entertainment', 'Free', true, 'seed', 'published', NOW()),
('AI Dungeon', 'https://aidungeon.io', 'AI驱动的文字冒险游戏', 'entertainment', 'Freemium', false, 'seed', 'published', NOW()),
('Suno', 'https://www.suno.ai', 'AI音乐生成工具', 'entertainment', 'Freemium', false, 'seed', 'published', NOW()),
('Udio', 'https://www.udio.com', 'AI音乐创作平台', 'entertainment', 'Freemium', false, 'seed', 'published', NOW()),
('ElevenLabs', 'https://elevenlabs.io', 'AI语音合成和克隆工具', 'entertainment', 'Freemium', false, 'seed', 'published', NOW()),
('HeyGen', 'https://www.heygen.com', 'AI数字人视频生成平台', 'entertainment', 'Paid', false, 'seed', 'published', NOW()),
('D-ID', 'https://www.d-id.com', 'AI数字人视频生成工具', 'entertainment', 'Paid', false, 'seed', 'published', NOW()),
('Runway', 'https://runwayml.com', 'AI视频生成和编辑平台', 'entertainment', 'Paid', false, 'seed', 'published', NOW()),
('Pika', 'https://pika.art', 'AI视频生成平台，支持文本和图像生成视频', 'entertainment', 'Freemium', false, 'seed', 'published', NOW());
